### ISSUE TITLE
Suggestion - Alternate way of use

### ISSUE THREAD

**Issue by coco9515** [xRoier/SCP-1162-EXILED#1]
I read 1162 to find a more RP way to use it - as it's to regain something lost and to lost something on you, so I suggest : 
- Having a configurable % of chance for it to spawn
- Having the ability to configure which room is the 1162 spawn.
- Having a message sent when you enter the room to notify you of 1162 presence.
- Not throwing an item to start it but rather stay in the room for X (configurable) seconds and not moving.
  - Randomly lost an item; if no items on the player, lost X (configurable) HP.
  - Limit to X (configurable) uses.

**Comment by xRoier** [comment]
Thanks for the ideas! I will take a look to implement some of them
